server:
  port: 10300

spring:
  application:
    name: gatewayservice

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:10100
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      queue: microservices2

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

security:
  origins:
    url: "*"
    max-age: 3600
    methods: GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD
    headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"