server:
  port: 10200

spring:
  application:
    name: discoveryservice
  security:
    user:
      name: guest
      password: guest

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:10100
  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      queue: microservices2

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
