server:
  port: 10600

spring:
  application:
    name: commentsservice

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:10100

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:13306/users_products_comments?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1

  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      queue: microservices2

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

logging:
  file:
    name: ${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  origins:
    url: "*"
    max-age: 3600
    methods: GET, POST, PUT, DELETE
    headers: Origin, Content-Type, Accept, Authorization
  claims:
    header-authorities: Authorities
    separator: --
  token:
    key: qwerty123456
    type: Bearer
    header-name: token
    validity: 1800000
