spring:

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      queue: microservices2

security:
  claims:
    header-authorities: Authorities
    separator: --
  token:
    key: qwerty123456
    type: Bearer
    header-name: token
    validity: 1800000