FROM openjdk:11-slim
COPY target/configuration-service-0.0.1-SNAPSHOT.jar configuration-service-0.0.1-SNAPSHOT.jar
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
#ENTRYPOINT ["java", "-jar", "/configuration-service-0.0.1-SNAPSHOT.jar"]
CMD /wait && java -jar /configuration-service-0.0.1-SNAPSHOT.jar