version: "3.8"

services:
     
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices2
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - microservices2
    depends_on:
      - prometheus

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 700m
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservices2
      
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    hostname: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices2

  database:
    image: mysql
    mem_limit: 700m
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_products_comments
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices2

  configuration:
    image: dockersentinel/configuration-service
    mem_limit: 700m
    depends_on:
      - zipkin
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: zipkin:9411, rabbitmq:5672
      SPRING_PROFILES_ACTIVE: native
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "10100:10100"
    hostname: configuration
    networks:
      - microservices2

  discovery:
    image: dockersentinel/discovery-service
    mem_limit: 700m
    depends_on:
      - configuration
      - rabbitmq
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: configuration:10100
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:10100/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "10200:10200"
    hostname: discovery
    networks:
      - microservices2

  gateway:
    image: dockersentinel/gateway-service
    mem_limit: 700m
    depends_on:
      - configuration
      - discovery
      - rabbitmq
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: configuration:10100
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:10100/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:10200/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "10300:10300"
    hostname: gateway
    networks:
      - microservices2

  users:
    image: dockersentinel/users-service
    mem_limit: 700m
    depends_on:
      - configuration
      - discovery
      - gateway
      - rabbitmq
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: configuration:10100, discovery:10200, gateway:10300, database:3306
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:10100/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:10200/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/users_products_comments?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "10400:10400"
    hostname: users
    networks:
      - microservices2

  products:
    image: dockersentinel/products-service
    mem_limit: 700m
    depends_on:
      - configuration
      - discovery
      - gateway
      - rabbitmq
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: configuration:10100, discovery:10200, gateway:10300, database:3306
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:10100/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:10200/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/users_products_comments?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "10500:10500"
    hostname: products
    networks:
      - microservices2

  comments:
    image: dockersentinel/comments-service
    mem_limit: 700m
    depends_on:
      - configuration
      - discovery
      - gateway
      - rabbitmq
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      WAIT_HOSTS: configuration:10100, discovery:10200, gateway:10300, database:3306
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configuration:10100/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:10200/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/users_products_comments?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "10600:10600"
    hostname: comments
    networks:
      - microservices2

networks:
  microservices2: