global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'usersservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['users:10400']
  - job_name: 'productsservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['products:10500']
  - job_name: 'commentsservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['comments:10600']